/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-12-09 05:40:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.TwitterGUI;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.airlinemgmt.beans.AirlineEmployee;

public final class CreateEmployee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form action=\"../EmployeeProcessor\" method=\"post\" class=\"well\">\r\n");
      out.write("<center>\r\n");
      out.write("\t<h2> Create New Employee</h2>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t");

		String errorMessage = "";
		if(session.getAttribute("error")!=null){
		errorMessage = (String) session.getAttribute("error");
		}
	
      out.write("\r\n");
      out.write("\t<label id=\"errorMessage\"><b>");
      out.print(errorMessage);
      out.write("</b></label>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

	AirlineEmployee emp=new AirlineEmployee();
	if (session.getAttribute("empObj")!=null)
	{
		emp=(AirlineEmployee)session.getAttribute("empObj");
	}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<h3>Personal Details</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table cellpadding=\"10px\" cellspacing=\"10px\" class=\"table-striped\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Name</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"First Name\" name=\"fName\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(emp.getfName()!=null?emp.getfName():"");
      out.write("\" class=\"form-control\" required=\"true\"></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Last Name\" name=\"lName\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(emp.getlName()!=null?emp.getlName():"");
      out.write("\" class=\"form-control\" required=\"true\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>SSN</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Social Security Info\"\r\n");
      out.write("\t\t\t\t\t\tname=\"ssn\" value=\"");
      out.print(emp.getSSN()!=null?emp.getSSN():"");
      out.write("\" class=\"form-control\" required=\"true\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Date of Birth</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-append date input-group form-control\" id=\"dp3\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-date=\"12-07-2012\" data-date-format=\"mm-dd-yyyy\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"span2\" name=\"dob\" size=\"16\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(emp.getHireDate() != null ? emp.getHireDate() : "");
      out.write("\" readonly> &nbsp;<span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"add-on glyphicon glyphicon-calendar\" required=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Contact Information</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Contact Information\"\r\n");
      out.write("\t\t\t\t\t\tname=\"cInfo\" value=\"");
      out.print(emp.getContactNo()!=null?emp.getContactNo():"");
      out.write("\" class=\"form-control\" required=\"true\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Address</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Address\" name=\"address\" value=\"");
      out.print(emp.getAddress()!=null?emp.getAddress():"");
      out.write("\" class=\"form-control\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>City</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"City\" name=\"city\" value=\"");
      out.print(emp.getCity()!=null?emp.getCity():"");
      out.write("\" class=\"form-control\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>State</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"State\" name=\"state\" value=\"");
      out.print(emp.getState()!=null?emp.getState():"");
      out.write("\" class=\"form-control\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Zip Code</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Zip Code\" name=\"zip\" value=\"");
      out.print(emp.getZipCode()!=null?emp.getZipCode():"");
      out.write("\" class=\"form-control\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h3>Work Information</h3>\r\n");
      out.write("\t\t<table cellpadding=\"10px\" cellspacing=\"10px\" class=\"table-striped\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Work Position</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"Work Position\" name=\"wTitle\" value=\"");
      out.print(emp.getPosition()!=null?emp.getPosition():"");
      out.write("\" class=\"form-control\" required=\"true\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Work Description</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<td><textarea placeholder=\"Work Description\" name=\"wDesc\" value=\"");
      out.print(emp.getWorkDesc()!=null?emp.getWorkDesc():"");
      out.write("\" class=\"form-control\" required=\"true\">\r\n");
      out.write("\t\t\t\t\t</textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Hire Date</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"input-append date input-group form-control\" id=\"dp1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-date=\"12-07-2012\" data-date-format=\"mm-dd-yyyy\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"span2\" name=\"hireDate\" size=\"16\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(emp.getHireDate() != null ? emp.getHireDate() : "");
      out.write("\" readonly> &nbsp;<span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"add-on glyphicon glyphicon-calendar\" required=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h3>Account Information</h3>\r\n");
      out.write("\t\t<table cellpadding=\"10px\" cellspacing=\"10px\" class=\"table-striped\" class=\" form-control\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\tUsername\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Username\" name=\"uName\" value=\"");
      out.print(emp.getUserName()!=null?emp.getUserName():"");
      out.write("\" class=\"form-control\" required=\"true\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\tPassword\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" placeholder=\"Username\" name=\"uPasswd\" value=\"");
      out.print(emp.getPassword()!=null?emp.getPassword():"");
      out.write("\" class=\"form-control\" required=\"true\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"submit\" class=\"btn btn-success\" value=\"Create Account\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br> <br> <br> <br> <br>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
