/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-12-09 12:23:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.TwitterGUI;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.airlinemgmt.beans.Reservation;
import com.airlinemgmt.beans.Traveller;

public final class PassengerInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=US-ASCII");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=US-ASCII\">\n");
      out.write("<title></title>\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("<link href=\"css/datepicker.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/prettify.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<form action=\"../PassengerProcessor\" method=\"post\" class=\"well\">\n");
      out.write("\t\t<center>\n");
      out.write("\t\t\t<h3>Passenger Info</h3>\n");
      out.write("\t\t\t<table cellpadding=\"10px\" cellspacing=\"10px\" class=\"table-striped\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>Passenger Name</td>\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"First Name\" name=\"fName\" class=\"form-control\" required=\"true\" ></td>\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Last Name\" name=\"lName\" class=\"form-control\" required=\"true\" ></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>ICard Type</td>\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"ICard Type\" name=\"idType\" class=\"form-control\" required=\"true\" ></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>ICard Info</td>\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"ICard Number\" name=\"idNum\" class=\"form-control\" required=\"true\" ></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<br /> <br /> <input type=\"submit\" class=\"btn btn-success\"\n");
      out.write("\t\t\t\tvalue=\"Add\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t</center>\n");
      out.write("\t</form>\n");
      out.write("<center>\n");
      out.write("\t");

		if (session.getAttribute("passengerList") != null &&((ArrayList<Traveller>)session.getAttribute("passengerList")).size()>0	) {
			ArrayList<Traveller> traveller=(ArrayList<Traveller>)session.getAttribute("passengerList");

	
      out.write("\n");
      out.write("\t<table class=\"table-striped\" cellpadding=\"10px\" width=\"800px\">\n");
      out.write("\n");
      out.write("\t\t<thead>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td><b>Passenger Name</b></td>\n");
      out.write("\t\t\t\t<td><b>ICard Type</b></td>\n");
      out.write("\t\t\t\t<td><b>ICard Info</b></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</thead>\n");
      out.write("\n");
      out.write("\t\t");

			int i=0;
			for (Traveller obj : traveller) {
				if(obj!=null){
		
      out.write("\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>");
      out.print(obj.getfName());
      out.write("&nbsp;");
      out.print(obj.getlName());
      out.write("&nbsp;</td>\n");
      out.write("\t\t\t<td>");
      out.print(obj.getNationality());
      out.write("</td>\n");
      out.write("\t\t\t<td>");
      out.print(obj.getPassNum());
      out.write("</td>\n");
      out.write("\t\t\t<td><form action=\"../PassengerProcessor\" method=\"get\">\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Delete\" class=\"btn btn-danger\" name=\"");
      out.print(i);
      out.write("\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t</td>\n");
      out.write("\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t");

				}
			i++;
			}
		
      out.write("\n");
      out.write("\n");
      out.write("\t</table>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t\n");
      out.write("\t\t\t");

		String errorMessage = "";
		if(session.getAttribute("error")!=null){
		errorMessage = (String) session.getAttribute("error");
		}
	
      out.write("\n");
      out.write("\t<label id=\"errorMessage\"><b>");
      out.print(errorMessage);
      out.write("</b></label>\n");
      out.write("\t<center><form action=\"../ReservationNav\" method=\"get\"><input type=\"submit\" value=\"Continue >>\" class=\"btn btn-success\"></form></center>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
