/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-12-09 11:22:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.TwitterGUI;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.airlinemgmt.beans.FlightDetails;
import com.airlinemgmt.beans.AirlineEmployee;

public final class SearchFlight_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form class=\"well\" action=\"../FlightListProcessor\" method=\"post\">\r\n");
      out.write("\t\t");

			FlightDetails flight = new FlightDetails();
			if (session.getAttribute("flightSearchObj") != null) {
				flight = (FlightDetails) session
						.getAttribute("flightSearchObj");
			}
		
      out.write("\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<h3>Flight Details</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table cellpadding=\"10px\" cellspacing=\"10px\" class=\"table-striped\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Airline</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Airline Name\" name=\"fName\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(flight.getAirlineName() != null ? flight.getAirlineName()
					: "");
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Source</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Source\" name=\"fSource\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(flight.getSrc() != null ? flight.getSrc() : "");
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Destination</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Destination\" name=\"fDestn\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(flight.getDest() != null ? flight.getDest() : "");
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Flight Number</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Flight Number\" name=\"fNum\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(flight.getFlightNum() != null ? flight.getFlightNum()
					: "");
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Flight Date</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Flight Date\" name=\"fDate\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(flight.getFlightDate() != null ? flight.getFlightDate()
					: "");
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Number of Seats</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Number of Seats\"\r\n");
      out.write("\t\t\t\t\t\tname=\"fSeats\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(flight.getNumOfSeats() != 0 ? flight.getNumOfSeats() : "");
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t\t<input type=\"submit\"  value=\"Search\" class=\"btn btn-success\">\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
