/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-12-09 12:23:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.TwitterGUI;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.airlinemgmt.beans.Reservation;

public final class TransactionInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=US-ASCII");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=US-ASCII\">\n");
      out.write("<title></title>\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("<link href=\"../css/datepicker.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"../css/prettify.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t");

	String fare="";
	if(session.getAttribute("myReservation")!=null)
	{
		Reservation reservation =(Reservation)session.getAttribute("myReservation");
		fare=reservation.getFare()+"";
	}
		
      out.write("\n");
      out.write("\t\n");
      out.write("\t<center>\n");
      out.write("\t<h2>Trip Summary</h2>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t\t<h3>Total Fare ");
      out.print(fare );
      out.write("</h3>\n");
      out.write("\t</center>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<form action=\"../TransactionProcessor\" method=\"post\" class=\"well\">\n");
      out.write("\t\t<center>\n");
      out.write("\t\t\t<h3>Transaction Info</h3>\n");
      out.write("\n");
      out.write("\t\t\t<table cellpadding=\"10px\" cellspacing=\"10px\" class=\"table-striped\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>Card Number</td>\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"Credit Card Number\"\n");
      out.write("\t\t\t\t\t\tname=\"cardNum\" class=\"form-control\" required=\"true\"></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>CVV</td>\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" placeholder=\"CVV\" name=\"cvv\" class=\"form-control\" required=\"true\"></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>Expire Date</td>\n");
      out.write("\t\t\t\t\t<td><div class=\"input-append date\" id=\"dpMonths\"\n");
      out.write("\t\t\t\t\t\t\tdata-date=\"102/2012\" data-date-format=\"mm/yyyy\"\n");
      out.write("\t\t\t\t\t\t\tdata-date-viewmode=\"years\" data-date-minviewmode=\"months\">\n");
      out.write("\t\t\t\t\t\t\t<input class=\"span2\" size=\"16\" name=\"expiryDate\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"02/2012\" readonly> &nbsp; <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"add-on glyphicon glyphicon-calendar\"></span>\n");
      out.write("\t\t\t\t\t\t</div></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<br /> <br /> <input type=\"submit\" class=\"btn btn-primary\"\n");
      out.write("\t\t\t\tvalue=\"Submit\">\n");
      out.write("\n");
      out.write("\t\t</center>\n");
      out.write("\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\t<script src=\"../js/prettify.js\"></script>\n");
      out.write("\t<script src=\"../js/jquery-1.9.1.js\"></script>\n");
      out.write("\t<script src=\"../js/bootstrap-datepicker.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\twindow.prettyPrint && prettyPrint();\n");
      out.write("\t\t\t$('#dp3').datepicker();\n");
      out.write("\t\t\t$('#dpMonths').datepicker();\n");
      out.write("\n");
      out.write("\t\t\tvar checkin = $('#dpd1').datepicker({\n");
      out.write("\t\t\t\tonRender : function(date) {\n");
      out.write("\t\t\t\t\treturn date.valueOf() < now.valueOf() ? 'disabled' : '';\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}).on('changeDate', function(ev) {\n");
      out.write("\t\t\t\tif (ev.date.valueOf() > checkout.date.valueOf()) {\n");
      out.write("\t\t\t\t\tvar newDate = new Date(ev.date)\n");
      out.write("\t\t\t\t\tnewDate.setDate(newDate.getDate() + 1);\n");
      out.write("\t\t\t\t\tcheckout.setValue(newDate);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tcheckin.hide();\n");
      out.write("\t\t\t\t$('#dpd2')[0].focus();\n");
      out.write("\t\t\t}).data('datepicker');\n");
      out.write("\t\t\tvar checkout = $('#dpd2')\n");
      out.write("\t\t\t\t\t.datepicker(\n");
      out.write("\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\tonRender : function(date) {\n");
      out.write("\t\t\t\t\t\t\t\t\treturn date.valueOf() <= checkin.date\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.valueOf() ? 'disabled' : '';\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t}).on('changeDate', function(ev) {\n");
      out.write("\t\t\t\t\t\tcheckout.hide();\n");
      out.write("\t\t\t\t\t}).data('datepicker');\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("\t<script src=\"http://www.google-analytics.com/urchin.js\"\n");
      out.write("\t\ttype=\"text/javascript\">\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t\t\t");

		String errorMessage = "";
		if(session.getAttribute("error")!=null){
		errorMessage = (String) session.getAttribute("error");
		}
	
      out.write("\n");
      out.write("\t<label id=\"errorMessage\"><b>");
      out.print(errorMessage);
      out.write("</b></label>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
