/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-12-08 11:13:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.TwitterGUI;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.airlinemgmt.beans.Traveller;
import com.airlinemgmt.beans.Journey;
import com.airlinemgmt.beans.FlightDetails;
import com.airlinemgmt.beans.AirlineEmployee;

public final class ViewFlight_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		FlightDetails flight = new FlightDetails();

		if (session.getAttribute("flightObj") != null) {
			flight = (FlightDetails) session.getAttribute("flightObj");
		}
	
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h2>View Flight</h2>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h3>Flight Details</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t<table cellpadding=\"10px\" cellspacing=\"10px\" class=\"well\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Airline</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(flight.getAirlineName());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Flight Number</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(flight.getFlightNum());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Source</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(flight.getSrc());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Destination</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(flight.getDest());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Flight Date</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(flight.getFlightDate());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Number of Seats</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(flight.getNumOfSeats());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Available Seats</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(flight.getAvailableSeats());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t");

		if (flight.getJourneyInfo() != null) {
			Journey[] journey = flight.getJourneyInfo();
	
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h4>\r\n");
      out.write("\t\t\t<b>Journeys For The Flight</b>\r\n");
      out.write("\t\t</h4>\r\n");
      out.write("\t\t<table class=\"table-striped\" width=\"800px\" cellpadding=\"10px\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td><b>Source</b></td>\r\n");
      out.write("\t\t\t\t\t<td><b>Destination</b></td>\r\n");
      out.write("\t\t\t\t\t<td><b>Take - Off Date</b></td>\r\n");
      out.write("\t\t\t\t\t<td><b>Landing Date</b></td>\r\n");
      out.write("\t\t\t\t\t<td><b>Fare</b></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[0].getBoardingPoint());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[0].getDestinationPoint());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[0].getDepartureDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[0].getArrivalDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[0].getFare());
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					for (int i = 1; i < journey.length; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[i].getBoardingPoint());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[i].getDestinationPoint());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[i].getDepartureDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[i].getArrivalDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[i].getFare());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t");

		if (flight.getPassengerInfo() != null) {
			Traveller[] journey = flight.getPassengerInfo();
			if (journey.length > 0) {
	
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h4>\r\n");
      out.write("\t\t\t<b>Passenger Information</b>\r\n");
      out.write("\t\t</h4>\r\n");
      out.write("\t\t<table class=\"table-striped\" width=\"800px\" cellpadding=\"10px\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td><b>Name</b></td>\r\n");
      out.write("\t\t\t\t\t<td><b>Identification</b></td>\r\n");
      out.write("\t\t\t\t\t<td><b>Identification Info</b></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					for (int i = 0; i < journey.length; i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[i].getfName());
      out.write("&nbsp;");
      out.print(journey[i].getlName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[i].getNationality());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(journey[i].getPassNum());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		}
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\r\n");
      out.write("\t\t<br> <br> <br>\r\n");
      out.write("\t\t<table cellpadding=\"10px\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><form action=\"../ViewFlight\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"<< Back\" class=\"btn btn-success\">\r\n");
      out.write("\t\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t\t<td><form action=\"../ViewFlight\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Modify\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
